name: branch pushed

on:
  push:
    branches:
      - "*"
      - "!*-release"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: "npm"
      - run: npm ci
        working-directory: ./functions
      - run: npm run lint
        working-directory: ./functions
      - run: npm run test
        working-directory: ./functions
      - run: npm run build
        working-directory: ./functions
